# Generated by Django 6.0.7 on 2026-09-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_seed_intro_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text='Last reminder email sent (dedup)', null=True),
        ),
    ]
