# Generated by Django 6.0.7 on 2026-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_last_reminded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Server-accumulated watch time for this lesson (seconds)'),
        ),
    ]
