# Generated by Django 6.0.7 on 2026-08-04 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_employee_id', message='Employee ID must be 3-20 characters using only uppercase letters and numbers (e.g. EMP001, ADMIN001).', regex='^[A-Z0-9]{3,20}$')], verbose_name='Employee ID'),
        ),
    ]
