# Generated by Django 6.0.7 on 2026-09-13 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_user', 'Approve user'), ('reject_user', 'Reject user'), ('create_user', 'Create user'), ('bulk_enroll', 'Bulk enroll'), ('assign_staff', 'Assign staff'), ('import_staff', 'Import staff'), ('course_create', 'Course create'), ('course_edit', 'Course edit'), ('course_delete', 'Course delete'), ('module_create', 'Module create'), ('module_edit', 'Module edit'), ('module_delete', 'Module delete'), ('lesson_create', 'Lesson create'), ('lesson_edit', 'Lesson edit'), ('lesson_delete', 'Lesson delete'), ('session_create', 'Session create'), ('session_edit', 'Session edit'), ('session_delete', 'Session delete'), ('certificate_issued', 'Certificate issued')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
